In [34]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
print(student_marks)
print(item_list)

[78, 47, 96, 55, 34]
['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']


In [4]:
hetero_list=[1,2,3.0,'text',True,3+2j]
hetero_list

[1, 2, 3.0, 'text', True, (3+2j)]

In [7]:
student_marks=[45,58,35,46,97,64]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[50, 63, 40, 51, 102, 69]


In [8]:
list1 = list(range(1,1000000))
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [10]:
list3 = list(range(3,1000001))
list3

[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,


In [15]:
%%time
import numpy as np
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
c=a+b

CPU times: total: 0 ns
Wall time: 22 ms


In [16]:
import numpy as np 
student_marks_arr=np.array([12,42,56,75,46,])
student_marks_arr

array([12, 42, 56, 75, 46])

In [17]:
import numpy as np 
horsepower=[130,45,85,46,71,]
horsepower_arr=np.array(horsepower)
horsepower_arr

array([130,  45,  85,  46,  71])

In [18]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [19]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape

(3, 5)

In [20]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype

dtype('int32')

In [21]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [17]:
import numpy as np
cars =np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]       

'buick skylark 320'

In [18]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [19]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [20]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0]

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U25')

In [21]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,1]

'buick skylark 320'

In [22]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,-1]

'ford torino'

In [2]:
import numpy as np
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [3]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [6]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2]

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [7]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:2, 3:5]

array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U25')

In [8]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr[0:3, 0:3]

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U25')

In [9]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  147.0


In [10]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Median horsepower = ",np.median(horsepower_arr))

Median horsepower =  150.0


In [11]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))

Minimum horsepower:  130
Maximum horsepower:  165


In [12]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Index of Minimum horsepower: ", np.argmin(horsepower_arr))
print("Index of Maximum horsepower: ", np.argmax(horsepower_arr))

Index of Minimum horsepower:  0
Index of Maximum horsepower:  1


In [13]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x) # gives the indices 
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [14]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
filter_arr = horsepower_arr > 135
newarr = horsepower_arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True  True  True  True]
[165 150 150 140]


In [15]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)

original array:  [130 165 150 150 140]
Sorted array:  [130 140 150 150 165]
original array after sorting:  [130 165 150 150 140]


In [16]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
horsepower_arr.sort()
print('original array after sorting: ', horsepower_arr)

original array:  [130 165 150 150 140]
original array after sorting:  [130 140 150 150 165]


In [5]:
import numpy as np 
hr_arr1 = np. array([130, 165, 150, 150, 140])
x = np.where(hr_arr1 >=150)
print(x)
print(hr_arr1[x])

(array([1, 2, 3], dtype=int64),)
[165 150 150]


In [25]:
student_marks=[[67,45],[90,92],[66,72],[32,40]]
student_marks_arr=np.array(student_marks)
student_marks_arr

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [26]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))

359


In [27]:
additional_marks = [2, 2, 5, 10, 1]
student_marks_arr += additional_marks
student_marks_arr

array([80, 94, 41, 74, 90])

In [28]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr = np.add(student_marks_arr, additional_marks)
student_marks_arr

array([80, 94, 41, 74, 90])

In [29]:
import numpy as np
array1=np.array([5, 10, 15])
array2=np.array([5])
array3= array1 * array2 
array3

array([25, 50, 75])

In [31]:
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks += [5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [32]:
student_marks=[[67,45],[90,92],[66,72],[32,40]]
student_marks_arr=np.array(student_marks)
students_marks += [5,10]
student_marks_arr

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [34]:
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [38]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [39]:
arr = np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50


In [40]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [46]:
np.zeros(200)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.zeros([10,10])


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
np.ones(40)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [57]:
np.ones([6,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.full(10,8)


array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [1]:
np.full([10,10],'numpy')

NameError: name 'np' is not defined

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.random.rand(6)

array([0.63409492, 0.66637017, 0.67086275, 0.32208418, 0.34515677,
       0.27982494])

In [66]:
np.random.randint(1,10, size=5)


array([3, 7, 1, 7, 2])

In [67]:
x = np.random.randint(100, size=(3, 5))
print(x)
print(type(x))


[[41 20 23 62 41]
 [99 59 59 32 42]
 [ 8 46  8 93 40]]
<class 'numpy.ndarray'>


In [68]:
x = np.random.choice([9, 3, 7, 5])
print(x)


3


In [69]:
x = np.random.choice([9, 3, 7, 5], size=(3, 5))   # sampling to create an nd-array 
print(x)
print(type(x))


[[9 7 9 9 9]
 [7 3 3 3 9]
 [5 7 9 5 5]]
<class 'numpy.ndarray'>


In [32]:
import numpy as np
#creating a 20 array
day_number = np.arange(1,11)
steps_walked=[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]
arr = np.array([day_number, steps_walked])
arr = arr.T
arr

TypeError: 'list' object is not callable