In [1]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
print(student marks)
print(item_list)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3881694935.py, line 3)

In [4]:
import numpy as np
#creating a 20 array
day_number = np.arange(1,11)
steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr = np.array([day_number, steps_walked])
arr = arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [5]:
new_arr= arr[:,1] + 2000
arr[:,1]=new_arr
arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [13]:
matched = arr[:,1]>9000
matched
new_arr = arr[matched]
new_arr

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [10]:
sortedArr =[arr[:,1].argsort()]
print('sorted 2D Numpy Array')
print(sortedArr)

sorted 2D Numpy Array
[array([4, 5, 0, 2, 6, 1, 3, 7, 8, 9], dtype=int64)]


In [14]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1)) 

10
[4 6]
[3 7]


In [15]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.mean(arr))
print(np.mean(arr, axis=0)) 

2.5
[2. 3.]


In [16]:
print(np.mean(arr, axis=1)) 

[1.5 3.5]


In [17]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.max(arr)) 
print(np.max(arr, axis=0)) 
print(np.max(arr, axis=1)) 
print(np.min(arr)) 
print(np.min(arr, axis=0))
print(np.min(arr, axis=1)) 

4
[3 4]
[2 4]
1
[1 2]
[1 3]


In [18]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.median(arr))
print(np.median(arr, axis=0))
print(np.median(arr, axis=1)) 

2.5
[2. 3.]
[1.5 3.5]


In [19]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.prod(arr))
print(np.prod(arr, axis=0))
print(np.prod(arr, axis=1))

24
[3 8]
[ 2 12]


In [20]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.std(arr)) 
print(np.std(arr, axis=0)) 
print(np.std(arr, axis=1)) 

1.118033988749895
[1. 1.]
[0.5 0.5]


In [27]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.var(arr)) 
print(np.var(arr, axis=0)) 
print(np.var(arr, axis=0))

1.25
[1. 1.]
[1. 1.]


In [22]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [23]:
import numpy as np
arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result) 

[3 3 3]


In [24]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [25]:
import numpy as np
arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])
result = arr1 / arr2
print(result) 

[2. 2. 2.]


In [26]:
import numpy as np
arr = np.array([2, 3, 4])
result = arr ** 2
print(result) 

[ 4  9 16]


In [28]:
import numpy as np
arr = np.array([4, 9, 16])
result = np.sqrt(arr)
print(result) 

[2. 3. 4.]


In [30]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 3])
result = arr1 == arr2
print(result) 

[False  True  True]


In [31]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result_mean = np.mean(arr)
result_std = np.std(arr, axis=1)
result_sum = np.sum(arr, axis=0)
print(result_mean)
print(result_std)
print(result_sum) 

3.5
[0.81649658 0.81649658]
[5 7 9]


In [32]:
import numpy as np
arr = np.array([2.3, 4.7, 6.1])
result = np.round(arr)
print(result) # Output: [2. 5. 6.]

[2. 5. 6.]


In [33]:
import numpy as np
arr = np.array([2, 3, 4])
result = np.power(arr, 2)
print(result)                                                                                      

[ 4  9 16]
