In [1]:
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
result = np.sort(arr)
print(result) # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [2]:
import numpy as np
arr = np.array([1, 5, 10])
result = np.where(arr < 5, arr, 0)
print(result)

[1 0 0]


In [4]:
quarterly_difference = S_Y - S_X
print(quarterly_difference)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [5]:
less_than_2 = S_X < 2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [6]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)

[[ 2  7 13 18]
 [ 4 12 18 23]]


In [13]:
X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
print( X_cumsum >= 8)
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
print( Y_cumsum >= 8)

[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


In [8]:
yearly_mean_X = np.mean(S_X, axis=1)
print(yearly_mean_X)

[4.5  5.75]


In [9]:
quarterly_mean_Y = np.mean(S_Y, axis=0)
print(quarterly_mean_Y)

[6.5 6.  5.5 6.5]


In [10]:
numbers = [1, 2, 3, 4, 5]
# Squaring each number using map()
squared_numbers = map(lambda x: x ** 2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [11]:
numbers = [1, 2, 3, 4, 5]
# Filtering even numbers using filter()
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))

[2, 4]


In [12]:
from functools import reduce
numbers = [1, 2, 3, 4, 5]
# Summing all the numbers using reduce()
sum_of_numbers = reduce(lambda x, y: x + y, numbers)
print(sum_of_numbers) 

15


In [1]:
# Squaring a number using a lambda function
numbers = [1, 2, 3, 4, 5]
square = lambda x: x ** 2
print(square(5))

25
